/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CarpetaInterfaz;

import javax.swing.JLabel;
import CarpetaClases.Cola;

/**
 *
 * @author Luisp
 */
public final class ColaInterfaz extends javax.swing.JPanel {

    /**
     * Creates new form ColaInterfaz
     * @param Nombre
     */
    
    public ColaInterfaz() {
        
        initComponents();
    }
    public ColaInterfaz(String Nombre) {
        initComponents();
        this.getTitulo().setText(Nombre);
    }

    public JLabel getContenidoCola() {
        return ContenidoCola;
    }


    public JLabel getTitulo() {
        return Titulo;
    }

    
    
    public void CambiarColaInterfaz(Cola Cola1){
        this.ContenidoCola.setText(Cola1.StringInterfaz());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContenidoCola = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 230, 200));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 69, 19), 2));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setText("Nombre de la Cola");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        ContenidoCola.setText("---");
        jScrollPane1.setViewportView(ContenidoCola);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 360, 40));

        jLabel2.setText("Fin");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel3.setText("Inicio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContenidoCola;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
