/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CarpetaInterfaz;
;

/**
 *
 * @author Luisp
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        colaInterfaz5 = new CarpetaInterfaz.ColaInterfaz();
        colaInterfaz6 = new CarpetaInterfaz.ColaInterfaz();
        colaInterfaz7 = new CarpetaInterfaz.ColaInterfaz();
        colaInterfaz8 = new CarpetaInterfaz.ColaInterfaz();
        colaInterfaz9 = new CarpetaInterfaz.ColaInterfaz();
        colaInterfaz10 = new CarpetaInterfaz.ColaInterfaz();
        colaInterfaz11 = new CarpetaInterfaz.ColaInterfaz();
        colaInterfaz12 = new CarpetaInterfaz.ColaInterfaz();
        personajeInterfaz1 = new CarpetaInterfaz.PersonajeInterfaz();
        personajeInterfaz3 = new CarpetaInterfaz.PersonajeInterfaz();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(colaInterfaz5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        jPanel1.add(colaInterfaz6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));
        jPanel1.add(colaInterfaz7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        jPanel1.add(colaInterfaz8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        jPanel1.add(colaInterfaz9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, -1, -1));
        jPanel1.add(colaInterfaz10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 400, -1, -1));
        jPanel1.add(colaInterfaz11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, -1, -1));
        jPanel1.add(colaInterfaz12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, -1, -1));
        jPanel1.add(personajeInterfaz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));
        jPanel1.add(personajeInterfaz3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(21);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(11);
        jSlider1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 370, -1));
        jSlider1.getAccessibleContext().setAccessibleName("");
        jSlider1.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setText("---");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 50, -1));

        jLabel2.setText("Peleas Ganadas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 90, -1));

        jLabel3.setText("---");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 530, 50, -1));

        jLabel4.setText("Peleas Ganadas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 90, -1));

        jLabel6.setText("Estado de la IA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CarpetaInterfaz.ColaInterfaz colaInterfaz10;
    private CarpetaInterfaz.ColaInterfaz colaInterfaz11;
    private CarpetaInterfaz.ColaInterfaz colaInterfaz12;
    private CarpetaInterfaz.ColaInterfaz colaInterfaz5;
    private CarpetaInterfaz.ColaInterfaz colaInterfaz6;
    private CarpetaInterfaz.ColaInterfaz colaInterfaz7;
    private CarpetaInterfaz.ColaInterfaz colaInterfaz8;
    private CarpetaInterfaz.ColaInterfaz colaInterfaz9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private CarpetaInterfaz.PersonajeInterfaz personajeInterfaz1;
    private CarpetaInterfaz.PersonajeInterfaz personajeInterfaz3;
    // End of variables declaration//GEN-END:variables
}
