/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CarpetaInterfaz;

import CarpetaClases.Personaje;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Luisp
 */
public class PersonajeInterfaz extends javax.swing.JPanel {

    /**
     * Creates new form PersonajeInterfaz
     */
    public PersonajeInterfaz() {
        initComponents();
    }
    
    public void ActualizarPersonjaeInterfaz(Personaje Personaje12) {
        this.getIndicadorResultado().setEnabled(false);
        this.getID().setText(Personaje12.getId());
    }
    
    public void CambiarIcono(Personaje Personaje12) {
        int contador = 1;
        this.Foto.setIcon(new ImageIcon("src\\assets\\"+contador+Personaje12.getEmpresa()+".png"));
        this.Poder.setText(Integer.toString(Personaje12.getGlobal()));
        contador++;
        if(contador == 11){
        contador = 1;
        }
    }
    
    public void CambiarIconoPelea() {
        this.IndicadorResultado.setIcon(new ImageIcon("src\\assets\\pelea.png"));
    }
    
    public void CambiarIconoGanador() {
        this.IndicadorResultado.setIcon(new ImageIcon("src\\assets\\ganador.png"));
    }
    
    public void CambiarIconoPerdedor() {
        this.IndicadorResultado.setIcon(new ImageIcon("src\\assets\\perderdor.png"));
    }
    public void CambiarIconoEmpate() {
        this.IndicadorResultado.setIcon(new ImageIcon("src\\assets\\empate.png"));
    }

    public JLabel getFoto() {
        return Foto;
    }

    public JLabel getID() {
        return ID;
    }

    public JLabel getIndicadorResultado() {
        return IndicadorResultado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        IndicadorResultado = new javax.swing.JLabel();
        Foto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Poder = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        ID.setText("---");
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        IndicadorResultado.setText("Indicador Resultado");
        jPanel1.add(IndicadorResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 40));

        Foto.setText("Fotos");
        jPanel1.add(Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 140));

        jLabel2.setText("Poder: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        Poder.setText("---");
        jPanel1.add(Poder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IndicadorResultado;
    private javax.swing.JLabel Poder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
